/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: rpc.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "rpc.pb-c.h"
void   call__init
                     (Call         *message)
{
  static const Call init_value = CALL__INIT;
  *message = init_value;
}
size_t call__get_packed_size
                     (const Call *message)
{
  assert(message->base.descriptor == &call__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t call__pack
                     (const Call *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &call__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t call__pack_to_buffer
                     (const Call *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &call__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Call *
       call__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Call *)
     protobuf_c_message_unpack (&call__descriptor,
                                allocator, len, data);
}
void   call__free_unpacked
                     (Call *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &call__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   return__init
                     (Return         *message)
{
  static const Return init_value = RETURN__INIT;
  *message = init_value;
}
size_t return__get_packed_size
                     (const Return *message)
{
  assert(message->base.descriptor == &return__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t return__pack
                     (const Return *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &return__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t return__pack_to_buffer
                     (const Return *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &return__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Return *
       return__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Return *)
     protobuf_c_message_unpack (&return__descriptor,
                                allocator, len, data);
}
void   return__free_unpacked
                     (Return *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &return__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   invert_arguments__init
                     (InvertArguments         *message)
{
  static const InvertArguments init_value = INVERT_ARGUMENTS__INIT;
  *message = init_value;
}
size_t invert_arguments__get_packed_size
                     (const InvertArguments *message)
{
  assert(message->base.descriptor == &invert_arguments__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t invert_arguments__pack
                     (const InvertArguments *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &invert_arguments__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t invert_arguments__pack_to_buffer
                     (const InvertArguments *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &invert_arguments__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InvertArguments *
       invert_arguments__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InvertArguments *)
     protobuf_c_message_unpack (&invert_arguments__descriptor,
                                allocator, len, data);
}
void   invert_arguments__free_unpacked
                     (InvertArguments *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &invert_arguments__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   invert_return_value__init
                     (InvertReturnValue         *message)
{
  static const InvertReturnValue init_value = INVERT_RETURN_VALUE__INIT;
  *message = init_value;
}
size_t invert_return_value__get_packed_size
                     (const InvertReturnValue *message)
{
  assert(message->base.descriptor == &invert_return_value__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t invert_return_value__pack
                     (const InvertReturnValue *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &invert_return_value__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t invert_return_value__pack_to_buffer
                     (const InvertReturnValue *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &invert_return_value__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InvertReturnValue *
       invert_return_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InvertReturnValue *)
     protobuf_c_message_unpack (&invert_return_value__descriptor,
                                allocator, len, data);
}
void   invert_return_value__free_unpacked
                     (InvertReturnValue *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &invert_return_value__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor call__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Call, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "args",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Call, args),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned call__field_indices_by_name[] = {
  1,   /* field[1] = args */
  0,   /* field[0] = name */
};
static const ProtobufCIntRange call__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor call__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Call",
  "Call",
  "Call",
  "",
  sizeof(Call),
  2,
  call__field_descriptors,
  call__field_indices_by_name,
  1,  call__number_ranges,
  (ProtobufCMessageInit) call__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor return__field_descriptors[2] =
{
  {
    "success",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Return, success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Return, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned return__field_indices_by_name[] = {
  0,   /* field[0] = success */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange return__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor return__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Return",
  "Return",
  "Return",
  "",
  sizeof(Return),
  2,
  return__field_descriptors,
  return__field_indices_by_name,
  1,  return__number_ranges,
  (ProtobufCMessageInit) return__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor invert_arguments__field_descriptors[1] =
{
  {
    "v",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(InvertArguments, v),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned invert_arguments__field_indices_by_name[] = {
  0,   /* field[0] = v */
};
static const ProtobufCIntRange invert_arguments__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor invert_arguments__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "InvertArguments",
  "InvertArguments",
  "InvertArguments",
  "",
  sizeof(InvertArguments),
  1,
  invert_arguments__field_descriptors,
  invert_arguments__field_indices_by_name,
  1,  invert_arguments__number_ranges,
  (ProtobufCMessageInit) invert_arguments__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor invert_return_value__field_descriptors[1] =
{
  {
    "notv",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(InvertReturnValue, notv),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned invert_return_value__field_indices_by_name[] = {
  0,   /* field[0] = notv */
};
static const ProtobufCIntRange invert_return_value__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor invert_return_value__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "InvertReturnValue",
  "InvertReturnValue",
  "InvertReturnValue",
  "",
  sizeof(InvertReturnValue),
  1,
  invert_return_value__field_descriptors,
  invert_return_value__field_indices_by_name,
  1,  invert_return_value__number_ranges,
  (ProtobufCMessageInit) invert_return_value__init,
  NULL,NULL,NULL    /* reserved[123] */
};
